apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: hpjsocw54-go 
  janus-idp.io/tekton: hpjsocw54-go
  backstage.io/kubernetes-id: hpjsocw54-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: hpjsocw54-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml