apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: hpjsocw54-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hpjsocw54-go 
  name: hpjsocw54-go
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: hpjsocw54-go
    weight: 100 
