apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hpjsocw54-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hpjsocw54-go 
  name: hpjsocw54-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hpjsocw54-go 
